### ISSUE TITLE
Suported 3d file format

### ISSUE THREAD

**Issue by Eragonfr** [mrDIMAS/rg3d#18]
What are the supported format, I'v seen many fbx files and png in the examples and in rusty-shooter there is also some tga, ogg and dae files.
But do you have a list of actually supported files format ?(in this crate and also in related crates, like rg3d-sound).
Do you plan to support more files format ? Like obj or jpg(if they aren't supported yet)

**Comment by mrDIMAS** [comment]
Good point, I should mention all supported formats in readme.
Currently engine supports these formats:

- Image formats (thanks to image crate): PNG, JPEG, GIF, BMP, ICO, TIFF, WebP, PNM, DDS (DXT1, DXT3, DXT5), TGA
- 3d models: more or less full support of FBX format (some exotic features can still be missing, because I never needed them)
- Sound: WAV (non-compressed only) and OGG (lewton crate)

That single DAE file you saw was added in repo by accident and there is no DAE support.

OBJ support is easy to add, however this format is very limiting - it has no animations, skinning, etc, so preferable 3d model format for engine is FBX. There is still no editor for engine, and FBX helps to solve this issue - it allows you to build complex scene in Blender for example and then load it directly in engine. You can check Sponza.fbx in `examples/data`, open it with Blender and you'll see what I mean.

**Comment by Eragonfr** [comment]
Ok, i can understand the choice of the fbx format, I know nothing about what format have what, and… I'm new in the 3d world(and the game dev world)
