### ISSUE TITLE
Supporting large maps files

### ISSUE THREAD

**Issue by Eragonfr** [mrDIMAS/rg3d#19]
I want to build an RPG on top of rg3d but, can I have an extremely large map ?  
Having a large map can cause issues with memory, so I was thinking about the possibility of charging only chunks of the map, but, is it possible with the actual state of the engine ?

**Comment by mrDIMAS** [comment]
There is very little support for such scenes, engine still does not have level-of-detail (LOD) system, which may cause some serious performance issues on large scenes. Also there is no map streaming for now, which means that everything will be loaded into memory at once. However, large scenes are possible with manual management of objects visibility, but can be tricky to do. Also in case of RPG you probably want to have some sort of terrain, but engine still does not have terrains, so everything has to be done in some 3d editor. 

All such stuff (LODs, terrains, streaming, etc) is on my TODO list, but it would be hard to use without editor, so currently I'm trying to make some simple scene editor which will help to setup everything properly. Also since I have fulltime job and do not have enough spare time, everything will be implemented not soon.

I'd advise you to create small maps first to create and test some basic mechanics or your game, and then start expanding them.

**Comment by Eragonfr** [comment]
Thank, for the response. And yes, I'm going to make small maps to test the mechanics.
