### ISSUE TITLE
Key input issue on mac

### ISSUE THREAD

**Issue by toyboot4e** [mrDIMAS/rg3d#32]
`winit` has key input issue on macOS: https://github.com/rust-windowing/winit/issues/1470

It says that macOS Accesibility prevents key inputs from going as `DeviceEvent`s. So, on macOS, keyboard input events can only be captured as `WindowEvent`, unless somehow configuring Accesibility.

I made a commit to enable key input on macOS in the `3rd_person` example: https://github.com/toyboot4e/rg3d/commit/2f2dafe3a3a049e2b01626ef6f4c9dc4354e43ce. I can make such changes and make a PR, but I'm not sure if it's good to get key input as `WindowEvent`.

**Comment by mrDIMAS** [comment]
This is sad, WindowEvent is bad because it requires mouse to be inside window bounds to get any events from it, so it is suitable only for full screen mode. However it seems that there is no other solutions, so yeah PR would be nice, but I'd add `#[cfg(target_os="macos")]` to WindowEvent branch and `#[cfg(not(target_os="macos"))]` to DeviceEvent branch, so to use DeviceEvent where possible and WindowEvent otherwise.

**Comment by toyboot4e** [comment]
> WindowEvent is bad because it requires mouse to be inside window bounds to get any events from it

Does it? My creature walks with WASD when my mouse is not on the window (if the window has focus). So I'm not seeing any particular problem on macOS. Hope this is a good news (or not on Windows?).

**Comment by mrDIMAS** [comment]
Keyboard input is working, right, mouse events won't come if cursor is outside window.

**Comment by toyboot4e** [comment]
Mouse events are still available as `DeviceEvent`s on macOS. How about handling mouse events via `DeviceEvent` while handling keyboard events via `WindowEvent`? Then we don't need `#[cfg]` branch.

If that's OK, I would make a PR and prepare for review.

**Comment by mrDIMAS** [comment]
Yeah, that sounds good.
